name: Scrape latest weather for Hilversum

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '3,23,43 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      # env:
      #   API_KEY: ${{ secrets.WEATHER_APIKEY }}
      run: |-
        curl "http://api.weatherapi.com/v1/current.json?key=${{ secrets.WEATHER_APIKEY }}&q=Hilversum&aqi=no" | jq . > weather.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
